"""add phase 2 user profile and activity models

Revision ID: 406e36fca7db
Revises: f9a575fbbce5
Create Date: 2026-07-14 02:12:51.270859

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "406e36fca7db"
down_revision: Union[
    str,
    Sequence[str],
    None,
] = "f9a575fbbce5"
branch_labels: Union[
    str,
    Sequence[str],
    None,
] = None
depends_on: Union[
    str,
    Sequence[str],
    None,
] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    is_postgresql = (
        bind.dialect.name == "postgresql"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "seed_key",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "name",
            sa.String(length=120),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
        ),
        sa.Column(
            "gender",
            sa.String(length=30),
            nullable=True,
        ),
        sa.Column(
            "age",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "avatar_url",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "onboarding_completed",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "is_synthetic",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table(
        "users",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_users_email"),
            ["email"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f("ix_users_id"),
            ["id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_users_seed_key"),
            ["seed_key"],
            unique=True,
        )

    op.create_table(
        "style_profiles",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "version",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "dna_vector",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "primary_identity",
            sa.String(length=100),
            nullable=False,
        ),
        sa.Column(
            "secondary_identity",
            sa.String(length=100),
            nullable=True,
        ),
        sa.Column(
            "profile_confidence",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "model_version",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id",
            "version",
            name="uq_style_profile_user_version",
        ),
    )

    with op.batch_alter_table(
        "style_profiles",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_style_profiles_user_id"
            ),
            ["user_id"],
            unique=False,
        )

    op.create_table(
        "user_preferences",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "budget_min",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "budget_max",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "budget_tier",
            sa.String(length=50),
            nullable=True,
        ),
        sa.Column(
            "preferred_colours",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "preferred_brands",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "preferred_occasions",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "preferred_aesthetics",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "fit_preferences",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "comfort_priority",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "trend_openness",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table(
        "user_preferences",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_user_preferences_user_id"
            ),
            ["user_id"],
            unique=True,
        )

    op.create_table(
        "wardrobe_items",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "seed_key",
            sa.String(length=120),
            nullable=True,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "source",
            sa.String(length=40),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(length=160),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "subcategory",
            sa.String(length=80),
            nullable=True,
        ),
        sa.Column(
            "primary_colour",
            sa.String(length=40),
            nullable=True,
        ),
        sa.Column(
            "size",
            sa.String(length=30),
            nullable=True,
        ),
        sa.Column(
            "image_url",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "tags",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "purchase_price",
            sa.Float(),
            nullable=True,
        ),
        sa.Column(
            "purchase_date",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "wear_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "last_worn_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table(
        "wardrobe_items",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_wardrobe_items_product_id"
            ),
            ["product_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_wardrobe_items_seed_key"
            ),
            ["seed_key"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_wardrobe_items_user_id"
            ),
            ["user_id"],
            unique=False,
        )

    op.create_table(
        "recommendation_sessions",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "style_profile_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "session_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "raw_prompt",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "parsed_intent",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "model_version",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["style_profile_id"],
            ["style_profiles.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table(
        "recommendation_sessions",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_recommendation_sessions_user_id"
            ),
            ["user_id"],
            unique=False,
        )

    op.create_table(
        "recommendation_items",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "session_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "rank",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "overall_score",
            sa.Float(),
            nullable=False,
        ),
        sa.Column(
            "score_breakdown",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "explanation",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "warning",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["recommendation_sessions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id",
            "rank",
            name="uq_recommendation_session_rank",
        ),
    )

    with op.batch_alter_table(
        "recommendation_items",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_recommendation_items_product_id"
            ),
            ["product_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_recommendation_items_session_id"
            ),
            ["session_id"],
            unique=False,
        )

    op.create_table(
        "user_events",
        sa.Column(
            "id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "seed_key",
            sa.String(length=150),
            nullable=True,
        ),
        sa.Column(
            "user_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "product_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "wardrobe_item_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "recommendation_item_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "event_type",
            sa.String(length=50),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_item_id"],
            ["recommendation_items.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["wardrobe_item_id"],
            ["wardrobe_items.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    with op.batch_alter_table(
        "user_events",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_user_events_event_type"
            ),
            ["event_type"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_user_events_occurred_at"
            ),
            ["occurred_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_user_events_product_id"
            ),
            ["product_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_user_events_seed_key"
            ),
            ["seed_key"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_user_events_user_id"
            ),
            ["user_id"],
            unique=False,
        )

    with op.batch_alter_table(
        "community_profiles",
        schema=None,
    ) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        batch_op.alter_column(
            "handle",
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        batch_op.alter_column(
            "avatar",
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        batch_op.alter_column(
            "dna_json",
            existing_type=sa.VARCHAR(),
            type_=sa.Text(),
            nullable=False,
        )
        batch_op.alter_column(
            "dna_label",
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        batch_op.alter_column(
            "recent_purchases",
            existing_type=sa.VARCHAR(),
            type_=sa.Text(),
            nullable=False,
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_community_profiles_handle"
            )
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_community_profiles_name"
            )
        )

    tags_type_options = {}
    occasions_type_options = {}

    if is_postgresql:
        tags_type_options[
            "postgresql_using"
        ] = """
            CASE
                WHEN tags IS NULL
                    OR BTRIM(tags) = ''
                THEN '[]'::json
                WHEN LEFT(
                    BTRIM(tags),
                    1
                ) IN ('[', '{')
                THEN tags::json
                ELSE TO_JSON(
                    STRING_TO_ARRAY(
                        tags,
                        ','
                    )
                )
            END
        """

        occasions_type_options[
            "postgresql_using"
        ] = """
            CASE
                WHEN occasions IS NULL
                    OR BTRIM(occasions) = ''
                THEN '[]'::json
                WHEN LEFT(
                    BTRIM(occasions),
                    1
                ) IN ('[', '{')
                THEN occasions::json
                ELSE TO_JSON(
                    STRING_TO_ARRAY(
                        occasions,
                        ','
                    )
                )
            END
        """

    with op.batch_alter_table(
        "products",
        schema=None,
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "sku",
                sa.String(length=64),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "description",
                sa.Text(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "category",
                sa.String(length=50),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "subcategory",
                sa.String(length=80),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "primary_colour",
                sa.String(length=40),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "gender_segment",
                sa.String(length=30),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "sizes",
                sa.JSON(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "stock_quantity",
                sa.Integer(),
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_active",
                sa.Boolean(),
                nullable=True,
            )
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        batch_op.alter_column(
            "brand",
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        batch_op.alter_column(
            "price",
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            nullable=False,
        )
        batch_op.alter_column(
            "originalPrice",
            existing_type=sa.INTEGER(),
            type_=sa.Float(),
            nullable=False,
        )
        batch_op.alter_column(
            "image",
            existing_type=sa.VARCHAR(),
            type_=sa.Text(),
            nullable=False,
        )
        batch_op.alter_column(
            "tags",
            existing_type=sa.VARCHAR(),
            type_=sa.JSON(),
            nullable=False,
            **tags_type_options,
        )
        batch_op.alter_column(
            "occasions",
            existing_type=sa.VARCHAR(),
            type_=sa.JSON(),
            nullable=False,
            **occasions_type_options,
        )
        batch_op.alter_column(
            "budgetTier",
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        batch_op.alter_column(
            "season",
            existing_type=sa.VARCHAR(),
            nullable=False,
        )
        batch_op.drop_index(
            batch_op.f("ix_products_brand")
        )
        batch_op.drop_index(
            batch_op.f("ix_products_name")
        )
        batch_op.create_index(
            batch_op.f(
                "ix_products_category"
            ),
            ["category"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_products_gender_segment"
            ),
            ["gender_segment"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_products_is_active"
            ),
            ["is_active"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_products_primary_colour"
            ),
            ["primary_colour"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_products_sku"),
            ["sku"],
            unique=True,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_products_subcategory"
            ),
            ["subcategory"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    is_postgresql = (
        bind.dialect.name == "postgresql"
    )

    tags_type_options = {}
    occasions_type_options = {}

    if is_postgresql:
        tags_type_options[
            "postgresql_using"
        ] = "tags::text"

        occasions_type_options[
            "postgresql_using"
        ] = "occasions::text"

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "products",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_products_subcategory"
            )
        )
        batch_op.drop_index(
            batch_op.f("ix_products_sku")
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_products_primary_colour"
            )
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_products_is_active"
            )
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_products_gender_segment"
            )
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_products_category"
            )
        )
        batch_op.create_index(
            batch_op.f("ix_products_name"),
            ["name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_products_brand"),
            ["brand"],
            unique=False,
        )
        batch_op.alter_column(
            "season",
            existing_type=sa.VARCHAR(),
            nullable=True,
        )
        batch_op.alter_column(
            "budgetTier",
            existing_type=sa.VARCHAR(),
            nullable=True,
        )
        batch_op.alter_column(
            "occasions",
            existing_type=sa.JSON(),
            type_=sa.VARCHAR(),
            nullable=True,
            **occasions_type_options,
        )
        batch_op.alter_column(
            "tags",
            existing_type=sa.JSON(),
            type_=sa.VARCHAR(),
            nullable=True,
            **tags_type_options,
        )
        batch_op.alter_column(
            "image",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            nullable=True,
        )
        batch_op.alter_column(
            "originalPrice",
            existing_type=sa.Float(),
            type_=sa.INTEGER(),
            nullable=True,
        )
        batch_op.alter_column(
            "price",
            existing_type=sa.Float(),
            type_=sa.INTEGER(),
            nullable=True,
        )
        batch_op.alter_column(
            "brand",
            existing_type=sa.VARCHAR(),
            nullable=True,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(),
            nullable=True,
        )
        batch_op.drop_column(
            "is_active"
        )
        batch_op.drop_column(
            "stock_quantity"
        )
        batch_op.drop_column(
            "sizes"
        )
        batch_op.drop_column(
            "gender_segment"
        )
        batch_op.drop_column(
            "primary_colour"
        )
        batch_op.drop_column(
            "subcategory"
        )
        batch_op.drop_column(
            "category"
        )
        batch_op.drop_column(
            "description"
        )
        batch_op.drop_column(
            "sku"
        )

    with op.batch_alter_table(
        "community_profiles",
        schema=None,
    ) as batch_op:
        batch_op.create_index(
            batch_op.f(
                "ix_community_profiles_name"
            ),
            ["name"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f(
                "ix_community_profiles_handle"
            ),
            ["handle"],
            unique=False,
        )
        batch_op.alter_column(
            "recent_purchases",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            nullable=True,
        )
        batch_op.alter_column(
            "dna_label",
            existing_type=sa.VARCHAR(),
            nullable=True,
        )
        batch_op.alter_column(
            "dna_json",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(),
            nullable=True,
        )
        batch_op.alter_column(
            "role",
            existing_type=sa.VARCHAR(),
            nullable=True,
        )
        batch_op.alter_column(
            "avatar",
            existing_type=sa.VARCHAR(),
            nullable=True,
        )
        batch_op.alter_column(
            "handle",
            existing_type=sa.VARCHAR(),
            nullable=True,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(),
            nullable=True,
        )

    with op.batch_alter_table(
        "user_events",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_user_events_user_id"
            )
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_user_events_seed_key"
            )
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_user_events_product_id"
            )
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_user_events_occurred_at"
            )
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_user_events_event_type"
            )
        )

    op.drop_table("user_events")

    with op.batch_alter_table(
        "recommendation_items",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_recommendation_items_session_id"
            )
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_recommendation_items_product_id"
            )
        )

    op.drop_table(
        "recommendation_items"
    )

    with op.batch_alter_table(
        "recommendation_sessions",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_recommendation_sessions_user_id"
            )
        )

    op.drop_table(
        "recommendation_sessions"
    )

    with op.batch_alter_table(
        "wardrobe_items",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_wardrobe_items_user_id"
            )
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_wardrobe_items_seed_key"
            )
        )
        batch_op.drop_index(
            batch_op.f(
                "ix_wardrobe_items_product_id"
            )
        )

    op.drop_table("wardrobe_items")

    with op.batch_alter_table(
        "user_preferences",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_user_preferences_user_id"
            )
        )

    op.drop_table("user_preferences")

    with op.batch_alter_table(
        "style_profiles",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_style_profiles_user_id"
            )
        )

    op.drop_table("style_profiles")

    with op.batch_alter_table(
        "users",
        schema=None,
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f(
                "ix_users_seed_key"
            )
        )
        batch_op.drop_index(
            batch_op.f("ix_users_id")
        )
        batch_op.drop_index(
            batch_op.f("ix_users_email")
        )

    op.drop_table("users")
    # ### end Alembic commands ###