"""enforce required product runtime fields

Revision ID: 6fcc67661214
Revises: 406e36fca7db
Create Date: 2026-07-14 02:45:03.020537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '6fcc67661214'
down_revision: Union[str, Sequence[str], None] = '406e36fca7db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('sizes',
               existing_type=sqlite.JSON(),
               nullable=False)
        batch_op.alter_column('stock_quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('stock_quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sizes',
               existing_type=sqlite.JSON(),
               nullable=True)

    # ### end Alembic commands ###
