"""create initial schema

Revision ID: f9a575fbbce5
Revises:
Create Date: 2026-07-13 14:15:11.785920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9a575fbbce5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('handle', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('dna_json', sa.String(), nullable=True),
    sa.Column('dna_label', sa.String(), nullable=True),
    sa.Column('recent_purchases', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('community_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_community_profiles_handle'), ['handle'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_profiles_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_community_profiles_name'), ['name'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('originalPrice', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('occasions', sa.String(), nullable=True),
    sa.Column('budgetTier', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index(batch_op.f('ix_products_brand'))

    op.drop_table('products')
    with op.batch_alter_table('community_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_community_profiles_name'))
        batch_op.drop_index(batch_op.f('ix_community_profiles_id'))
        batch_op.drop_index(batch_op.f('ix_community_profiles_handle'))

    op.drop_table('community_profiles')
    # ### end Alembic commands ###
