export const decisionFixture = {
  snapshot_id: '11111111-1111-4111-8111-111111111111',
  recommendation_item_id: 41,
  session_id: 9,
  product: {
    id: 1,
    sku: 'PHASE4-001',
    name: 'Minimal Campus Shirt',
    brand: 'Test Brand',
    description: 'Minimal casual shirt',
    price: 1499,
    originalPrice: 1999,
    image: 'https://example.com/shirt.jpg',
    category: 'top',
    subcategory: 'shirt',
    primary_colour: 'white',
    tags: ['minimalist', 'casual'],
    occasions: ['campus'],
    budgetTier: 'mid_range',
    season: 'all_season',
  },
  overall_score: 88,
  score_breakdown: {
    style: {
      score: 90,
      weight: 0.35,
      weighted_score: 31.5,
      evidence_source: 'style_profile',
      evidence: { matched_styles: ['minimalist'] },
    },
    occasion: {
      score: 100,
      weight: 0.2,
      weighted_score: 20,
      evidence_source: 'request_context',
      evidence: { requested_occasion: 'campus' },
    },
    budget: {
      score: 100,
      weight: 0.2,
      weighted_score: 20,
      evidence_source: 'user_preferences',
      evidence: { budget_min: 800, budget_max: 3000 },
    },
    wardrobe: {
      score: 60,
      weight: 0.15,
      weighted_score: 9,
      evidence_source: 'wardrobe_items',
      evidence: { wardrobe_item_count: 0 },
    },
    season: {
      score: 100,
      weight: 0.1,
      weighted_score: 10,
      evidence_source: 'request_context',
      evidence: { requested_season: 'summer' },
    },
  },
  explanation: {
    summary: 'This is a strong match for your current Fashion DNA.',
    reasons: [
      {
        code: 'style_match',
        title: 'Alignment with your Minimalist DNA',
        detail: 'The product shares minimalist with your saved profile.',
        score: 90,
        evidence_source: 'style_profile',
      },
    ],
    limitations: [
      'Community purchase behaviour was not used because no verified aggregate source is available.',
    ],
  },
  evidence_sources: {},
  regret_signals: [
    {
      code: 'wardrobe_duplicate',
      severity: 'medium',
      title: 'Similar item already in your wardrobe',
      detail: 'Your wardrobe contains one matching item.',
      evidence: { duplicate_count: 1 },
    },
  ],
  model_version: 'decision-v1.0.0',
  profile_version: 3,
  created_at: '2026-07-16T10:00:00Z',
};
